name: Deploy docs to GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Generate docs
        run: npm run typedoc:index

      - name: Update pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: docs
          path: typedoc-output/
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pages: write

    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs
