name: Publish develop package to GitHub package registry
on:
  push:
    branches:
      - capacitor-calendar-110_Publish_dev_releases_from_develop_on_github_package_registry
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get current timestamp
        run: |
          TIMESTAMP=$(date +"%S%M%H%d%m%y")
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Construct new dev version
        run: |
          NEW_VERSION="${{ env.VERSION }}-dev.${{ env.TIMESTAMP }}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Print new version
        run: echo "New version is ${{ env.NEW_VERSION }}"

      - name: Run npm version
        run: npm version ${{ env.NEW_VERSION }} --no-git-tag-version

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
